### ISSUE TITLE
OpenSource Onboarding Checklist

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/monique-monosynth#1]
This is just a checklist for myself about onboarding

- [x] get my branch ready to go and swap it to main
   - [x] cherry pick tommys patch diff onto that branch
   - [x] Clearly mark all my hacks as "// PORT_HACK FIXME"
   - [x] introduce a CLA and put it in the readme
   - [x] Update the README with CLA and Build instructions
   - [x] call main 'original'
   - [x] call j6b or whatever main
- [x] make repo public then we can make our own forks. 
- [x] Repo perms: Add surge team at appropriate write and triage levels
- [ ] Deal with vst2 and Asio  opt im
- [x] Build on linux and win
- [x] setup azure pipelines for pr At least
- [x] Discord git channel
- [ ] start opening some issues

**Comment by baconpaul** [comment]
The discord should be done
